version: '3'

services:
    composer:
        build: config/docker/php
        environment:
            COMPOSER_CACHE_DIR: /scripts/var/cache/composer
            COMPOSER_MEMORY_LIMIT: -1
        volumes:
            - ./:/scripts
        working_dir: /scripts
        user: '1000'
        env_file:
            - .env
        networks:
            - default
        entrypoint: ["/usr/local/bin/composer"]

    web:
        image: nginx:alpine
        labels:
            traefik.backend: "web_sf4"
            traefik.port: "80"
            traefik.docker.network: "reverse-proxy"
            traefik.enable: "true"
            traefik.frontend.rule: "Host:sf4.127.0.0.1.nip.io"
        volumes:
            - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ./:/scripts:ro
        networks:
            - reverse-proxy
            - default
        depends_on:
            - app

    app:
        build: config/docker/php
        user: '1000'
        working_dir: /scripts
        volumes:
            - ./:/scripts:rw
            - ./config/docker/php/local.conf.d/dev.ini:/usr/local/etc/php/conf.d/dev.ini
        env_file:
          - .env
        depends_on:
            - databaseserver
        networks:
            - default

    console:
        build: config/docker/php
        user: '1000'
        working_dir: /scripts
        volumes:
            - ./:/scripts/:rw
        entrypoint: 'php bin/console'
        env_file:
          - .env
        depends_on:
            - databaseserver
        networks:
            - default

    databaseserver:
        image: mariadb:10.3.8
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: databasesf4
            MYSQL_ROOT_PASSWORD: passwordroot
        volumes:
            - databaseserverdata:/var/lib/mysql
        networks:
            - reverse-proxy
            - default

    adminer:
        image: adminer:standalone
        labels:
            traefik.backend: "adminer_sf4"
            traefik.port: "8080"
            traefik.docker.network: "reverse-proxy"
            traefik.enable: "true"
            traefik.frontend.rule: "Host:adminer.127.0.0.1.nip.io"
        networks:
            - reverse-proxy
            - default
        depends_on:
            - databaseserver


    mailserver:
        image: mailhog/mailhog
        labels:
            traefik.backend: "mailhog"
            traefik.port: "8025"
            traefik.docker.network: "reverse-proxy"
            traefik.enable: "true"
            traefik.frontend.rule: "Host:mail.127.0.0.1.nip.io"
        networks:
            - reverse-proxy
            - default

    behat:
        build: config/docker/php
        user: '1000'
        volumes:
            - ./:/scripts
        working_dir: /scripts
        entrypoint: ./vendor/bin/behat
        depends_on:
            - databaseservertest
        env_file:
            - .env
            - .env.test

    yarn:
        image: node:10-alpine
        working_dir: /scripts
        volumes:
            - ./:/scripts
        entrypoint:
            - yarn

    webpack:
        image: node:10-alpine
        working_dir: /scripts
        volumes:
            - ./:/scripts
        entrypoint: yarn encore dev --watch

    phpcs:
        build: config/docker/php
        volumes:
            - ./:/scripts
        working_dir: /scripts
        entrypoint: ./vendor/bin/phpcs --colors -d memory_limit=-1 --extensions=php --standard=config/phpcs/ruleset.xml -sp
        command: --colors src/ features/

    databaseservertest:
        image: mariadb:10.3.8
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: databasesf4test
            MYSQL_ROOT_PASSWORD: passwordroot
        tmpfs: /var/lib/mysql

networks:
    reverse-proxy:
        external:
            name: reverse-proxy


volumes:
    databaseserverdata:
        external:
            name: databaseserverdata
